Description: >
  Cloudformation Template to create ECS Repositories
Parameters:
  EnvironmentName:
    Description: Environment Name that will prefix to each resource name
    Type: String
    Default: uat
    AllowedValues:
      - uat
      - prod
  ModuleName:
    Description: Module name to tag to all resouces
    Type: String
  RepositoryName:
    Description: Repository Name
    Type: String
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowPushPull"
            Effect: Allow
            Principal:
              AWS:
                - arn:aws:iam::885586407638:user/CICD
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
              - "ecr:DescribeRepositories"
              - "ecr:GetRepositoryPolicy"
              - "ecr:ListImages"
              - "ecr:DescribeImages"
              - "ecr:DeleteRepository"
              - "ecr:BatchDeleteImage"
              - "ecr:SetRepositoryPolicy"
              - "ecr:DeleteRepositoryPolicy"
Outputs:
  RepositoryName:
    Description: Repository Name
    Value: !Ref RepositoryName
  RepositoryUri:
    Description: Repository Uri
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}